title = "Custom rules for student repos"
report = "gitleaks-report.json"

[[rules]]
id = "generic-db-pass"
description = "Likely database password"
regex = '''(?i)\b(DB_PASS|DATABASE_PASSWORD|PGPASSWORD|MYSQL_PASSWORD)\s*[:=]\s*['"]?[A-Za-z0-9_!@#$%^&*+=\-]{8,}['"]?'''
tags = ["secrets", "database"]

[[rules]]
id = "dotenv-secrets"
description = ".env style key/value with secret-ish names"
regex = '''(?i)\b(SECRET|TOKEN|API[_-]?KEY|ACCESS[_-]?KEY|PRIVATE[_-]?KEY)\b\s*[:=]\s*.+'''
tags = ["secrets", "env"]

[allowlist]
paths = [
  '''^docs/''',
  '''^tests?/fixtures?/''',
]