name: Secret scan (Gitleaks)

on:
  push:
    branches: ['**']                 
  pull_request:
    branches: ['**']                 

permissions:
  contents: read                    
  actions: read

jobs:
  gitleaks:
    name: Gitleaks detect
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0             

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: >
            detect
            --no-color --redact --verbose
            --exit-code 1
            --config=.gitleaks.toml

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          if-no-files-found: ignore
